#!/bin/bash

FMILIB=/home/mf/opt/HPCOM/fmilib2.0.1
ECLIPSE=Eclipse CDT4 - Unix Makefiles
LOCAL_LIB=/usr/local/lib64/
LOCAL_INC=/usr/local/include

#OSG 3.4.0 (Packages: 3.2.0, which is too old)
OSG_INCLUDE_DIR=${LOCAL_INC}
OSG_LIBRARY=${LOCAL_LIB}/libosg.so

OSGDB_INCLUDE_DIR=${LOCAL_INC}
OSGDB_LIBRARY=${LOCAL_LIB}/libosgDB.so

OSGGA_INCLUDE_DIR=${LOCAL_INC}
OSGGA_LIBRARY=${LOCAL_LIB}/libosgGA.so

OSGQT_INCLUDE_DIR=${LOCAL_INC}
OSGQT_LIBRARY=${LOCAL_LIB}/libosgQt.so

OSGUTIL_INCLUDE_DIR=${LOCAL_INC}
OSGUTIL_LIBRARY=${LOCAL_LIB}/libosgUtil.so

OSGVIEWER_INCLUDE_DIR=${LOCAL_INC}
OSGVIEWER_LIBRARY=${LOCAL_LIB}/libosgViewer.so

OPENTHREADS_INCLUDE_DIR=${LOCAL_INC}
OPENTHREADS_LIBRARY=${LOCAL_LIB}/libOpenThreads.so


cmake -DFMILIB_HOME=${FMILIB} -G"Eclipse CDT4 - Unix Makefiles" -DBUILD_DOCUMENTATION=true -DCMAKE_BUILD_TYPE=Debug \
-DOSG_INCLUDE_DIR=${OSG_INCLUDE_DIR} -DOSG_LIBRARY=${OSG_LIBRARY} \
-DOSGDB_INCLUDE_DIR=${OSGDB_INCLUDE_DIR} -DOSGDB_LIBRARY=${OSGDB_LIBRARY} \
-DOSGGA_INCLUDE_DIR=${OSGGA_INCLUDE_DIR} -DOSGGA_LIBRARY=${OSGGA_LIBRARY} \
-DOSGQT_INCLUDE_DIR=${OSGQT_INCLUDE_DIR} -DOSGQT_LIBRARY=${OSGQT_LIBRARY} \
-DOSGUTIL_INCLUDE_DIR=${OSGUTIL_INCLUDE_DIR} -DOSGUTIL_LIBRARY=${OSGUTIL_LIBRARY} \
-DOSGVIEWER_INCLUDE_DIR=${OSGVIEWER_INCLUDE_DIR} -DOSGVIEWER_LIBRARY=${OSGVIEWER_LIBRARY} \
-DOPENTHREADS_INCLUDE_DIR=${OPENTHREADS_INCLUDE_DIR} -DOPENTHREADS_LIBRARY=${OPENTHREADS_LIBRARY} \
../OMVis.git/
